---
- name: Deploy PHP App on Production Server
  hosts: prod_server
  become: yes
  tasks:

   - name: Pull latest Docker Image
     shell: docker pull harithayalamati/php-app:latest

   - name: Stop the existing contianer(if running)
     shell: docker rm -f php-app || true

   - name: Run the docker container
     shell: docker run -d --name php-app -p 80:80 harithayalamati/php-app:latest
